### ISSUE TITLE
0.8.0: ReferenceError: exports is not defined in ES module scope

### ISSUE THREAD

**Issue by mduft** [kevcodez/gradle-upgrade-interactive#8]
Installing the "new" 0.8.0 results in this error for me:

```
mduft@fril0666 /work/workspaces/deployment/deployment $ gradle-upgrade-interactive 
file:///home/mduft/.nvm/versions/node/v20.9.0/lib/node_modules/gradle-upgrade-interactive/buildFiles.js:7
  exports.buildFiles = buildFiles;
  ^

ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/mduft/.nvm/versions/node/v20.9.0/lib/node_modules/gradle-upgrade-interactive/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at getBuildFiles (file:///home/mduft/.nvm/versions/node/v20.9.0/lib/node_modules/gradle-upgrade-interactive/buildFiles.js:7:3)
    at file:///home/mduft/.nvm/versions/node/v20.9.0/lib/node_modules/gradle-upgrade-interactive/index.js:37:20
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.9.0
```

Just to be sure, I also tried with older node.js LTS versions (18 & 16) with the same result. Downgrading to 0.7.4 brings it back to working order :)

**Comment by kevcodez** [comment]
Could you retry with 0.8.2?

**Comment by mduft** [comment]
```
mduft@fril0666 /work/workspaces/deployment/deployment $ npm install -g gradle-upgrade-interactive@0.8.2

added 14 packages, removed 6 packages, and changed 43 packages in 5s

19 packages are looking for funding
  run `npm fund` for details
mduft@fril0666 /work/workspaces/deployment/deployment $ 
mduft@fril0666 /work/workspaces/deployment/deployment $ 
mduft@fril0666 /work/workspaces/deployment/deployment $ gradle-upgrade-interactive 
node:internal/errors:497
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'colors' imported from /home/mduft/.nvm/versions/node/v20.9.0/lib/node_modules/gradle-upgrade-interactive/index.js
    at new NodeError (node:internal/errors:406:5)
    at packageResolve (node:internal/modules/esm/resolve:789:9)
    at moduleResolve (node:internal/modules/esm/resolve:838:20)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.9.0
mduft@fril0666 /work/workspaces/deployment/deployment $ 
```

just ping me to test things :D

**Comment by kevcodez** [comment]
![Screenshot 2023-11-21 at 14 14 18](https://github.com/kevcodez/gradle-upgrade-interactive/assets/14073399/f9fbbec5-2c23-4597-9451-5d89b07ed067)

Hmmm odd - same Node version + installation worked for me

**Comment by kevcodez** [comment]
Just added the colors dependency that was missing for whatever reason and published 0.8.3

**Comment by mduft** [comment]
Aaaand tadaa :D works :D Thanks! That was blazingly fast.

**Comment by kevcodez** [comment]
Thanks for confirming!
